import type { Metadata } from 'next'
import { Fira_Code } from 'next/font/google'

const firaCode = Fira_Code({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
  variable: '--font-fira-code',
})

export const metadata: Metadata = {
  title: 'Kinalone Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={firaCode.variable}>
      <body className={firaCode.className}>{children}</body>
    </html>
  )
}
