import type { Metadata } from 'next'
import { Fira_Code } from 'next/font/google'
import Script from 'next/script'
import { themeInitScript } from './lib/theme'
import './globals.css'

const firaCode = Fira_Code({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
  variable: '--font-fira-code',
})

export const metadata: Metadata = {
  title: 'Kinalone Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={firaCode.variable} suppressHydrationWarning>
      <body className={firaCode.className}>
        <Script id="theme-init" strategy="beforeInteractive">
          {themeInitScript}
        </Script>
        {children}
      </body>
    </html>
  )
}
