name: CI Branch - Le Journal
on:
  push:
    branches:
      - '**'
      - '!main'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun lint
