name: CI Branch - Kinalone Dev
on:
  push:
    branches:
      - '**'
      - '!main'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.16
      - run: sudo bun install
      - run: bun lint
