name: CD Kinalone Dev
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
jobs:
  build:
    name: 'build-kinalone-dev'
    runs-on: ubuntu-latest

    steps:
      - uses: oven-sh/setup-bun@v1
      - name: Lint/test
        run: |
          bun install
          bun lint
