name: CD Kinalone Dev
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
jobs:
  build:
    name: 'build-kinalone-dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint/test
        run: |
          bun install 
          bun lint
